"""
SAM Alignment Parser for Bowtie2 CRISPR Off-Target Discoveries.
Extracts reference coordinates, strand, CIGAR, mismatch counts, and exact mismatch positions.
"""
import re
from typing import List, Dict, Any, Optional, Tuple


class SAMParser:
    """
    Parses SAM format lines generated by Bowtie2 into structured alignment records.
    """

    @staticmethod
    def parse_sam_line(line: str) -> Optional[Dict[str, Any]]:
        """
        Parses a single SAM record line (skipping header lines starting with '@').
        Returns dictionary of alignment fields or None if unmapped/header.
        """
        line_clean = line.strip()
        if not line_clean or line_clean.startswith("@"):
            return None

        fields = line_clean.split("\t")
        if len(fields) < 11:
            return None

        qname = fields[0]
        flag = int(fields[1])
        rname = fields[2]
        pos = int(fields[3])
        mapq = int(fields[4])
        cigar = fields[5]
        rnext = fields[6]
        pnext = int(fields[7])
        tlen = int(fields[8])
        seq = fields[9]
        qual = fields[10]
        tags = fields[11:]

        # Bit 4 (0x4) indicates unmapped read
        if flag & 4:
            return None

        # Bit 16 (0x10) indicates reverse strand mapping
        strand = "-" if (flag & 16) else "+"

        # Parse optional tags
        tag_dict = {}
        for tag in tags:
            parts = tag.split(":", 2)
            if len(parts) == 3:
                tag_name, tag_type, tag_val = parts
                if tag_type == "i":
                    tag_dict[tag_name] = int(tag_val)
                else:
                    tag_dict[tag_name] = tag_val

        # Mismatch count from NM or XM tag
        mismatch_count = tag_dict.get("NM", tag_dict.get("XM", 0))
        md_string = tag_dict.get("MD", "")

        # Parse mismatch positions from MD tag or CIGAR/Sequence
        mismatch_positions = SAMParser.extract_mismatch_positions_from_md(md_string, len(seq))

        return {
            "query_name": qname,
            "flag": flag,
            "chromosome": rname,
            "position": pos, # 1-based start
            "strand": strand,
            "mapq": mapq,
            "cigar": cigar,
            "aligned_sequence": seq,
            "mismatch_count": int(mismatch_count),
            "mismatch_positions": mismatch_positions,
            "md_tag": md_string,
            "tags": tag_dict
        }

    @staticmethod
    def extract_mismatch_positions_from_md(md_string: str, seq_len: int) -> List[int]:
        """
        Parses Bowtie2 MD:Z tag (e.g. '15A4', '10C3G5', '20') to extract 1-based mismatch coordinates.
        Coordinates are 1-based indexed from 5' to 3' of the guide sequence (1 to 20).
        """
        if not md_string:
            return []

        mismatch_positions = []
        current_pos = 0

        # Tokens: numbers (matches) or single letters (mismatches) or ^seq (deletions)
        tokens = re.findall(r'(\d+|\^[A-Za-z]+|[A-Za-z])', md_string)
        for token in tokens:
            if token.isdigit():
                current_pos += int(token)
            elif token.startswith("^"):
                # Deletion in reference
                current_pos += len(token) - 1
            elif token.isalpha() and len(token) == 1:
                # Single nucleotide mismatch in reference
                current_pos += 1
                if current_pos <= seq_len:
                    mismatch_positions.append(current_pos)

        return sorted(mismatch_positions)

    @classmethod
    def parse_sam_output(cls, sam_text: str) -> List[Dict[str, Any]]:
        """Parses multi-line SAM text into list of alignment records."""
        records = []
        for line in sam_text.splitlines():
            parsed = cls.parse_sam_line(line)
            if parsed is not None:
                records.append(parsed)
        return records
